### ISSUE TITLE
Location not updated while app in the background

### ISSUE THREAD

**Issue by imramsuthakar** [sachinvarma/EasyLocation#1]
Hi I have enabled the "  private boolean runAsBackgroundService = true;" in the main activity but my app in the background it doesn't update the location, but when I'm in the foreground it will be working fine

**Comment by SezerFidanci** [comment]
Hi, change runAsBackgroundService  value

`private boolean runAsBackgroundService = true;
`
and 

Remove this line
 `EventBus.getDefault().unregister(this); `

**Comment by imramsuthakar** [comment]
This issue not closed, it will still occur samsung and vivo devices, Location stops automatically within 10 mins while app goes background
